export taup_path

const EARTH_R_MAJOR_WGS84_KM = 6378.137

function _parse_taup_path_segment(segment; earth_radius_km=EARTH_R_MAJOR_WGS84_KM)
    seg = reduce(hcat, segment)
    degree = Float64.(seg[1, :])
    depth = earth_radius_km .- Float64.(seg[2, :])
    time = Float64.(seg[3, :])
    return degree, depth, time
end

"""
    taup_path_to_json(phase; kwargs...)

Generate `taup path` data in JSON format and save it to `filepath`.

kwargs:
- `model`: velocity model including "iasp91", "prem", "ak135", "ak135fcont", "ak135favg"
- `depth`: source depth in kilometers
- `deg`: epicentral distance in degrees
- `filepath`: output JSON file path
"""
function taup_path_to_json(
    phase::Union{AbstractString,AbstractVector{<:AbstractString}};
    model::String="ak135",
    depth::Real=0,
    deg::Union{Real,AbstractVector{<:Real}}=0,
    filepath::String="tmp_taup_path.json",
)
    phases = isa(phase, AbstractVector) ? String.(phase) : [String(phase)]
    degrees = isa(deg, AbstractVector) ? Float64.(deg) : [Float64(deg)]

    models = ["iasp91", "prem", "ak135", "ak135fcont", "ak135favg"]
    if !(model in models)
        error("Model $model is not recognized. Choose from: $(join(models, ", "))")
    end

    args = [
        "taup",
        "path",
        "--json",
        "-h",
        string(depth),
        "--mod",
        model,
        "-p",
        join(phases, ","),
        "--deg",
        join(string.(degrees), ","),
        "--output",
        filepath,
    ]

    run(Cmd(args))
end

"""
    parse_taup_path_json(filepath::String) -> TauPPath

Parse the TauP path JSON file generated by `taup_path_to_json` and return a `TauPPath` struct.
"""
function parse_taup_path_json(filepath::String)
    data = JSON.parsefile(filepath)

    model = String(get(data, "model", "unknown"))
    source_depths = Float64.(get(data, "sourcedepthlist", []))
    receiver_depths = Float64.(get(data, "receiverdepthlist", []))
    phases = String.(get(data, "phases", []))

    arrivals = RayArrival[]
    for arrival_data in get(data, "arrivals", [])
        path_segments = RayPathSegment[]
        for path_data in get(arrival_data, "path", [])
            degree, depth, time = _parse_taup_path_segment(path_data["segment"])
            push!(
                path_segments,
                RayPathSegment(
                    String(path_data["name"]),
                    String(path_data["wavetype"]),
                    degree,
                    depth,
                    time,
                ),
            )
        end

        push!(
            arrivals,
            RayArrival(
                String(arrival_data["phase"]),
                Float64(arrival_data["distdeg"]),
                Float64(arrival_data["time"]),
                Float64(arrival_data["rayparam"]),
                path_segments,
            ),
        )
    end

    return TauPPath(model, source_depths, receiver_depths, phases, arrivals)
end

"""
    taup_path(phase; kwargs...) -> TauPPath

Generate TauP raypath data for a phase or phases and return it as a `TauPPath` struct.

Keyword arguments:
- `model`: velocity model, including `"iasp91"`, `"prem"`, `"ak135"`,
  `"ak135fcont"`, and `"ak135favg"`
- `depth`: source depth in kilometers
- `deg`: epicentral distance or distances in degrees
"""
function taup_path(
    phase::Union{AbstractString,AbstractVector{<:AbstractString}}; kwargs...
)
    filepath = tempname() * ".json"
    try
        taup_path_to_json(phase; filepath=filepath, kwargs...)
        return parse_taup_path_json(filepath)
    finally
        rm(filepath; force=true)
    end
end
