export taup_curve, phase_diff
export split_monotonic_parts, split_PKP_branches

"""
    taup_curve_to_json(phase::String; kwargs...)

Generate `taup curve` data in JSON format and save it to `filepath`.

kwargs:
- `x` & `y`: axis data types
- `model`: velocity model including "iasp91", "prem", "ak135", "ak135fcont", "ak135favg"
- `depth`: source depth in kilometers
- `reddeg` & `redkm`: reducing velocity in deg/sec or km/sec
- `rel`: reference phase
- `xminmax` & `yminmax`: axis limits like: [0, 200]
- `filepath`: output JSON file path

Axes supports: "radian", "radian180", "degree", "degree180", "kilometer", "kilometer180", "rayparamrad", "rayparamdeg", "rayparamkm", "time", "tau", "takeoffangle", "incidentangle", "turndepth", "amp", "amppsv", "ampsh", "geospread", "refltran", "refltranpsv", "refltransh", "index", "tstar", "attenuation", "theta", "energygeospread", "pathlength", "radiation", "radiationpsv", "radiationsh"

For details, see: https://taup.readthedocs.io/en/latest/taup_curve.html
"""
function taup_curve_to_json(
    phase::String;
    x::String="degree180",
    y::String="time",
    model::String="iasp91",
    depth::T=0,
    filepath::String="tmp_taup_curve.json",
    reddeg::Union{T,Nothing}=nothing,
    redkm::Union{T,Nothing}=nothing,
    rel::Union{String,Nothing}=nothing,
    xminmax::Union{AbstractVector,Nothing}=nothing,
    yminmax::Union{AbstractVector,Nothing}=nothing,
) where {T<:Real}
    # assert args
    models = ["iasp91", "prem", "ak135", "ak135fcont", "ak135favg"]
    # if !(model in models)
    #     error("Model $model is not recognized. Choose from: $(join(models, ", "))")
    # end
    # commented out to allow custom models
    axes = [
        "radian",
        "radian180",
        "degree",
        "degree180",
        "kilometer",
        "kilometer180",
        "rayparamrad",
        "rayparamdeg",
        "rayparamkm",
        "time",
        "tau",
        "takeoffangle",
        "incidentangle",
        "turndepth",
        "amp",
        "amppsv",
        "ampsh",
        "geospread",
        "refltran",
        "refltranpsv",
        "refltransh",
        "index",
        "tstar",
        "attenuation",
        "theta",
        "energygeospread",
        "pathlength",
        "radiation",
        "radiationpsv",
        "radiationsh",
    ]
    if !(x in axes)
        error("X axis $x is not recognized. Choose from: $(join(axes, ", "))")
    end
    if !(y in axes)
        error("Y axis $y is not recognized. Choose from: $(join(axes, ", "))")
    end

    # construct command
    args = ["taup", "curve", "--json", "--phase", phase]

    if reddeg !== nothing
        push!(args, "--reddeg", string(reddeg))
    end
    if redkm !== nothing
        push!(args, "--redkm", string(redkm))
    end
    if rel !== nothing
        push!(args, "--rel", rel)
    end

    push!(args, "-x", x)
    push!(args, "-y", y)

    if xminmax !== nothing
        push!(args, "--xminmax", string(xminmax[1]), string(xminmax[2]))
    end
    if yminmax !== nothing
        push!(args, "--yminmax", string(yminmax[1]), string(yminmax[2]))
    end

    push!(args, "--model", model)

    push!(args, "-h", string(depth))

    push!(args, "--output", filepath)

    cmd = Cmd(args)
    run(cmd)
end

"""
    _extract_depth_from_description(description::String) -> Float64

Extract the source depth in kilometers from the TauP curve description string.
Expects a format like "... source depth of 100.0 kilometers ...".
"""
function _extract_depth_from_description(description::String)
    m = match(r"source depth of\s+([\d\.]+)\s+kilometers", description)

    if m !== nothing
        return parse(Float64, m.captures[1])
    else
        return NaN
    end
end

"""
    parse_taup_curve_json(filepath::String) -> Vector{TauPCurve}

Parse the TauP curve JSON file generated by `taup_curve_to_json` and return a vector of `TauPCurve` structs.

If the curve contains triplications, it will be split into monotonic parts.
"""
function parse_taup_curve_json(filepath::String)
    raw_data = JSON.parsefile(filepath)

    @assert length(raw_data["phases"]) ==
            length(raw_data["sourcedepthlist"]) ==
            length(raw_data["receiverdepthlist"]) ==
            1

    model = get(raw_data, "model", "unknown")
    src_dep = first(Float64.(get(raw_data, "sourcedepthlist", [])))
    rec_dep = first(Float64.(get(raw_data, "receiverdepthlist", [])))
    phase = first(String.(get(raw_data, "phases", [])))

    c = raw_data["curves"][1]

    xlabel = c["x"]
    ylabel = c["y"]
    description = c["description"]

    x = Float64.(c["segments"][1]["x"])
    y = Float64.(c["segments"][1]["y"])

    parts = split_monotonic_parts(x, y)

    return [
        TauPCurve(
            model,
            phase,
            src_dep,
            rec_dep,
            description,
            xlabel,
            ylabel,
            part.x,
            part.y,
        )
        for part in parts
    ]
end

"""
    taup_curve(phase::String; kwargs...) -> Vector{TauPCurve}

Generate TauP curve data for a given phase and return it as a `TauPCurve` struct.

`PKPab` and `PKPbc` may be requested directly. TauPUtils computes the full
`PKP` curve and returns only the corresponding branch.

kwargs:
- `x` & `y`: axis data types
- `model`: velocity model including "iasp91", "prem", "ak135", "ak135fcont", "ak135favg"
- `depth`: source depth in kilometers
- `reddeg` & `redkm`: reducing velocity in deg/sec or km/sec
- `rel`: reference phase
- `xminmax` & `yminmax`: axis limits

`x` and `y` supports: "radian", "radian180", "degree", "degree180", "kilometer", "kilometer180", "rayparamrad", "rayparamdeg", "rayparamkm", "time", "tau", "takeoffangle", "incidentangle", "turndepth", "amp", "amppsv", "ampsh", "geospread", "refltran", "refltranpsv", "refltransh", "index", "tstar", "attenuation", "theta", "energygeospread", "pathlength", "radiation", "radiationpsv", "radiationsh"

For details, see: https://taup.readthedocs.io/en/latest/taup_curve.html
"""
function taup_curve(phase::String; kwargs...)
    filepath = tempname() * ".json"
    try
        taup_phase = phase in ("PKPab", "PKPbc") ? "PKP" : phase
        taup_curve_to_json(taup_phase; filepath=filepath, kwargs...)
        curves = parse_taup_curve_json(filepath)

        if phase == "PKPab"
            isempty(curves) && error("TauP returned no PKPab branch")
            curve = curves[1]
            return [
                TauPCurve(
                    curve.model,
                    phase,
                    curve.source_depth,
                    curve.receiver_depth,
                    curve.description,
                    curve.xlabel,
                    curve.ylabel,
                    curve.x,
                    curve.y,
                ),
            ]
        elseif phase == "PKPbc"
            length(curves) < 2 && error("TauP returned no PKPbc branch")
            curve = curves[2]
            return [
                TauPCurve(
                    curve.model,
                    phase,
                    curve.source_depth,
                    curve.receiver_depth,
                    curve.description,
                    curve.xlabel,
                    curve.ylabel,
                    curve.x,
                    curve.y,
                ),
            ]
        end

        return curves
    finally
        rm(filepath; force=true)
    end
end

"""
    split_monotonic_parts(x, y)

Split the given x and y data into monotonic parts for separating triplications.
"""
function split_monotonic_parts(x, y)
    @assert length(x) == length(y)
    @assert length(x) ≥ 2

    dx = diff(x)

    @assert all(!iszero, dx)

    # example:
    # let dx = [-2, -1, 1, 2], then
    #      s = [-1, -1, 1, 1]  and
    #     ds =    [0, 2, 0]
    sdx = sign.(dx)
    splitidx = findall(diff(sdx) .!= 0)

    starts = vcat(1, splitidx .+ 1)
    stops = vcat(splitidx .+ 1, length(x))

    result = NamedTuple[];
    for (i, j) in zip(starts, stops)
        # if x is decreasing, reverse it to make it increasing for interpolation
        if x[i] > x[j]
            push!(result, (x=reverse(x[i:j]), y=reverse(y[i:j])))
        else
            push!(result, (x=x[i:j], y=y[i:j]))
        end
    end

    return result
end

"""
    split_PKP_branches(c::TauPCurve) -> NamedTuple
"""
function split_PKP_branches(c::TauPCurve)
    @assert c.phase == "PKP"

    branches = split_monotonic_parts(c.x, c.y)

    c_PKPab = TauPCurve(c.model, "PKPab", c.source_depth, c.receiver_depth, c.description, c.xlabel, c.ylabel, branches[1].x, branches[1].y)
    c_PKPbc = TauPCurve(c.model, "PKPbc", c.source_depth, c.receiver_depth, c.description, c.xlabel, c.ylabel, branches[2].x, branches[2].y)

    result = (
        PKPab=c_PKPab,
        PKPbc=c_PKPbc,
    )

    return result
end

"""
    phase_diff(phase1::String, phase2::String; depth=0, model="ak135", km=false)
    -> NamedTuple(ps, ddeg, dtime, deg1, time1, deg2, time2)

Calculate the phase difference between two seismic phases using TauP curves.

See Figure 15 of Tkalčić et al. (2020) for a visual representation of the phase difference.
- Tkalčić, H., Phạm, T.-S., & Wang, S. (2020). The Earth’s coda correlation wavefield: Rise of the new paradigm and recent advances. Earth-Science Reviews, 208, 103285. https://doi.org/10.1016/j.earscirev.2020.103285
"""
function phase_diff(
    phase1::String, phase2::String; depth=0, model="ak135", km=false, dp=0.01
)
    ystr = km ? "kilometer" : "degree"

    deg1s = taup_curve(phase1; depth=depth, model=model, x="rayparamdeg", y=ystr)
    deg2s = taup_curve(phase2; depth=depth, model=model, x="rayparamdeg", y=ystr)
    time1s = taup_curve(phase1; depth=depth, model=model, x="rayparamdeg", y="time")
    time2s = taup_curve(phase2; depth=depth, model=model, x="rayparamdeg", y="time")

    @assert length(deg1s) == length(time1s)
    @assert length(deg2s) == length(time2s)

    results = NamedTuple[]

    for (deg1, time1) in zip(deg1s, time1s),
        (deg2, time2) in zip(deg2s, time2s)

        # shared ray-parameter range
        pmin = max(minimum(deg1.x), minimum(deg2.x))
        pmax = min(maximum(deg1.x), maximum(deg2.x))

        # no overlap between these branches
        pmin > pmax && continue

        ps = pmin:dp:pmax

        # x is already increasing
        deg1_itp = LinearInterpolation(deg1.x, deg1.y)
        time1_itp = LinearInterpolation(time1.x, time1.y)
        deg2_itp = LinearInterpolation(deg2.x, deg2.y)
        time2_itp = LinearInterpolation(time2.x, time2.y)

        deg1_ = deg1_itp.(ps)
        time1_ = time1_itp.(ps)
        deg2_ = deg2_itp.(ps)
        time2_ = time2_itp.(ps)

        push!(
            results,
            (
                ps=ps,
                ddeg=deg1_ - deg2_,
                dtime=time1_ - time2_,
                deg1=deg1_,
                time1=time1_,
                deg2=deg2_,
                time2=time2_,
            ),
        )
    end

    return results
end
